# Generated by Django 3.1.2 on 2021-09-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Название канала')),
                ('avatar', models.ImageField(default='images/profile.png', upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=300, null=True, verbose_name='Описание канала')),
            ],
            options={
                'verbose_name': 'Каналы',
                'verbose_name_plural': 'Канал',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст коментария')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Коментарии постов',
                'verbose_name_plural': 'Коментарий поста',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст поста')),
                ('views', models.IntegerField(default=0, verbose_name='Кол-во просмотров')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
            ],
            options={
                'verbose_name': 'Посты каналов',
                'verbose_name_plural': 'Пост канала',
            },
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videos/', verbose_name='Видио поста')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Видио постов',
                'verbose_name_plural': 'Видио поста',
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография поста')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Фотографии постов',
                'verbose_name_plural': 'Фотография поста',
            },
        ),
    ]
