# Generated by Django 3.2.7 on 2021-09-23 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщение',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.ManyToManyField(blank=True, null=True, related_name='archive', to=settings.AUTH_USER_MODEL)),
                ('deleted', models.ManyToManyField(blank=True, related_name='deleted', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('push_notification', models.ManyToManyField(blank=True, related_name='push_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Диалоги',
                'verbose_name_plural': 'Диалог',
            },
        ),
        migrations.CreateModel(
            name='MessegePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фотография сообщения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.thread')),
            ],
            options={
                'verbose_name': 'Фотографии сообщений',
                'verbose_name_plural': 'Фотография сообщения',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.thread'),
        ),
        migrations.AddField(
            model_name='message',
            name='who_deleted_the_message',
            field=models.ManyToManyField(related_name='who_deleted_the_message', to=settings.AUTH_USER_MODEL),
        ),
    ]
