# Generated by Django 3.2.7 on 2021-10-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='date_of_last_message',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
