# Generated by Django 3.1.2 on 2021-09-14 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0002_auto_20210915_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='push_notification',
        ),
        migrations.AddField(
            model_name='thread',
            name='push_notification',
            field=models.ManyToManyField(related_name='push_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
