# Generated by Django 3.2.7 on 2021-09-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatarimageprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addit_image', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
